<?php

declare(strict_types=1);

namespace Andersundsehr\FrontendStudio\Service\Snapshot;

use TYPO3\CMS\Backend\Routing\UriBuilder;
use TYPO3\CMS\Core\Crypto\HashAlgo;

/**
 * Give generated backend URLs synthetic route tokens in snapshot HTML only.
 *
 * CLI routes otherwise contain dummyToken, while authenticated backend routes
 * contain session-specific hashes. Fresh hashes with TYPO3's normal token shape
 * keep formatting identical and let both samples detect the token as dynamic.
 *
 * FrontendRenderer::render() calls normalize() before HTML formatting. Inheritance
 * provides read access to UriBuilder's protected generated-URL cache, so only URLs
 * generated by TYPO3 are rewritten. The builder, form protection and live preview
 * output remain untouched; cached URLs may be reused across multiple samples.
 *
 * @see FrontendRenderer::render()
 */
final class BackendRouteTokens extends UriBuilder
{
    public static function normalize(string $html, UriBuilder $uriBuilder): string
    {
        $replacements = [];
        $seed = random_bytes(32);
        foreach ($uriBuilder->generated as $uri) {
            if (preg_match('~(?:^|&)token=(?:dummyToken|[a-f0-9]{64})(?:&|$)~i', $uri->getQuery()) !== 1) {
                continue;
            }

            $original = (string)$uri;
            $token = HashAlgo::SHA3_256->hash($original . $seed);
            $query = preg_replace('~(^|&)token=[^&]*~', '$1token=' . $token, $uri->getQuery());
            $replacement = (string)$uri->withQuery($query ?? $uri->getQuery());
            $replacements[$original] = $replacement;
            $replacements[htmlspecialchars($original, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8')] = htmlspecialchars($replacement, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
        }

        if ($replacements === []) {
            return $html;
        }

        // Match complete URL values, retaining unrelated URLs and literal token text.
        return preg_replace_callback('~[^\s<>"\']+~', static fn(array $match): string => $replacements[$match[0]] ?? $match[0], $html) ?? $html;
    }
}
