services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Andersundsehr\FrontendStudio\:
    resource: '../Classes/*'

  Andersundsehr\FrontendStudio\Service\ComponentPreviewRendererInterface:
    alias: Andersundsehr\FrontendStudio\Service\ComponentPreviewRenderer

  Andersundsehr\FrontendStudio\Service\ComponentPathResolverInterface:
    alias: Andersundsehr\FrontendStudio\Service\ComponentPathResolver

  Andersundsehr\FrontendStudio\Service\PreviewTypoScriptContextBuilderInterface:
    alias: Andersundsehr\FrontendStudio\Service\PreviewTypoScriptContextBuilder
